config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  resources :categories, except: [:show]
  resources :clients, except: [:show]
  resources :suppliers, except: [:show]
  resources :products
  resources :sales
  resources :warehouses
  resources :profiles, only: %w[show edit update]

  get 'buscar_producto/:termino', to: 'products#buscador'
  get '/buscador_clientes/:termino', to: 'clients#buscador'
  get '/buscador_proveedores/:termino', to: 'suppliers#buscador'
  post 'add_item_venta', to: 'sales#add_item'
  post 'add_cliente_venta', to: 'sales#add_client'
  post 'add_item_almacen', to: 'warehouses#add_item'
  post 'add_proveedor_entrada', to: 'warehouses#add_proveedor'
  post '/search', to: 'search#results'
  get '/search', to: 'home#index'

  #match '*unmatched', to: 'application#not_found_method', via: %i[get post]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def results
    @productos = Product.buscador(params[:termino])
    @clientes = Client.buscador(params[:termino])
    @proveedores = Supplier.buscador(params[:termino])
  end
end

app/views/search/results.html.erb
<div class="card shadow mb-4">
  <div class="cart-body">
    <div class="table-responsive">
      <table class="table table-bordered mb-0" id="tablaSuppliers" style="width: 100%;">
        <% if @productos.present? %>
          <thead>
          <tr>
            <th>Nombre producto</th>
            <th>Existencia</th>
            <th>Precio</th>
            <th>Categoria</th>
            <th>Proveedor</th>
            <th>Mostrar</th>
          </tr>
          </thead>
          <tbody>
          <% @productos.each do |prod| %>
            <tr>
              <td><%= prod.nombre %></td>
              <td><%= prod.existencia %></td>
              <td>$<%= prod.precio %></td>
              <td><%= prod.category != nil ? prod.category.nombre : "No tiene categoria" %></td>
              <td><%= prod.supplier != nil ? prod.supplier.nombre : "No tiene proveedor" %></td>
              <td>
                <%= link_to product_path(prod), class: "btn btn-info btn-sm" do %>
                  <i class="fas fa-eye"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
        <% if @proveedores.present? %>
          <thead>
          <tr>
            <th>Nombre de Proveedor</th>
            <th>Dirección</th>
            <th>Teléfono</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <% @proveedores.each do |supplier| %>
            <tr>
              <td><%= supplier.nombre %></td>
              <td><%= truncate(supplier.direccion, length: 150) %></td>
              <td><%= supplier.telefono %></td>
              <td>
                <%= link_to edit_client_path(supplier), remote: true, class: 'btn btn-info btn-sm', data: { 'bs-toggle': 'modal', 'bs-target': '#modalSuppliers' } do %>
                  <span class="fas fa-pencil"></span>
                <% end %>
                <%= link_to supplier, remote: true, method: :delete, data: { confirm: "¿Borrar proveedor?: #{supplier.nombre}?" }, class: 'btn btn-danger btn-sm' do %>
                  <span class="fas fa-trash"></span>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        <% end %>
        <% if @clientes.present? %>
          <thead>
          <tr>
            <th>Nombre de Cliente</th>
            <th>Dirección</th>
            <th>Teléfono</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <% @clientes.each do |client| %>
            <tr>
              <td><%= client.nombre %></td>
              <td><%= truncate(client.direccion, length: 150) %></td>
              <td><%= client.telefono %></td>
              <td>
                <%= link_to edit_client_path(client), remote: true, class: 'btn btn-info btn-sm', data: { 'bs-toggle': 'modal', 'bs-target': '#modalClients' } do %>
                  <span class="fas fa-pencil"></span>
                <% end %>
                <%= link_to client, remote: true, method: :delete, data: { confirm: "¿Borrar cliente?: #{client.nombre}?" }, class: 'btn btn-danger btn-sm' do %>
                  <span class="fas fa-trash"></span>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>