config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  resources :categories, except: [:show]
  resources :clients, except: [:show]
  resources :suppliers, except: [:show]
  resources :products
  resources :sales
  resources :warehouses
  resources :profiles, only: %w[show edit update]

  get 'buscar_producto/:termino', to: 'products#buscador'
  get '/buscador_clientes/:termino', to: 'clients#buscador'
  get '/buscador_proveedores/:termino', to: 'suppliers#buscador'
  post 'add_item_venta', to: 'sales#add_item'
  post 'add_cliente_venta', to: 'sales#add_client'
  post 'add_item_almacen', to: 'warehouses#add_item'
  post 'add_proveedor_entrada', to: 'warehouses#add_proveedor'
  post '/search', to: 'search#results'
  get '/search', to: 'home#index'

  #match '*unmatched', to: 'application#not_found_method', via: %i[get post]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: categories
#
#  id          :bigint           not null, primary key
#  descripcion :string
#  nombre      :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# categories controller
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[edit update destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.json { head :created }
        format.js
      else
        format.json { render json: @category.errors.full_messages, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.json { head :ok }
        format.js
      else
        format.json { render json: @category.errors.full_messages, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:nombre, :descripcion)
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

# categories helper
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for @category, remote: true do |f| %>
  <div class="mb-3">
    <h4 class="control-label">Datos de la categoría</h4>
  </div>

  <div class="item <%= 'has-error has-feedback' if @category.errors[:nombre].any? %>">
    <%= f.label 'Nombre de Categoría: ' %>
    <%= f.input :nombre, class: 'form-control', placeholder: 'Introduzca el nombre de la categoría...', label: false, input_html: {class: 'first-input'} %>
    <% if @category.errors[:nombre].any? %>
      <p class="bg-danger"><%= @category.errors[:nombre].to_s[/\w([^"]*)/] %></p>
    <% end %>
  </div>

  <div class="item <%= 'has-error has-feedback' if @category.errors[:descripcion].any? %>">
    <%= f.label "Descripción de la categoría: " %>
    <%= f.input :descripcion, class: 'form-control', placeholder: 'Introduzca la descripción de la categoría...', label: false, as: :text, input_html: {rows: 5} %>
    <% if @category.errors[:descripcion].any? %>
      <p class="bg-danger"><%= @category.errors[:descripcion].to_s[/\w[^"]*/] %></p>
    <% end %>
  </div>

  <div class="actions col-sm-9 p-0">
    <%= f.submit @category.new_record? ? "Crear Categoría" : "Actualizar Categoría", class: 'btn btn-success', data: {'bs-dismiss': "modal"} %>
  </div>
<% end %>

app/views/categories/_modal_categories.html.erb
<!-- Modal -->
<div class="modal fade" id="modalCategories" tabindex="-1" role="dialog" aria-labelledby="modalCategoriesLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-categories-title">Modal title</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body-categories modal-body" id="modal-body-categories">

      </div>
      <div class="modal-footer" id="modal-footer-categories">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/categories/create.js.erb
$('#tablaCategories').append(
    '<tr id="categoria_<%= @category.id %>">' +
    '<td><%= @category.nombre %></td>' +
    '<td><%= @category.descripcion %></td>' +
    '<td>' +
    '<%= link_to edit_category_path(@category), remote: true, class: "btn btn-info btn-sm", data: {"bs-toggle": "modal", "bs-target": "#modalCategories"} do %>' +
    '<span class="fas fa-pencil"></span>' +
    '<% end %>' +
    '<%= link_to @category, remote: true, method: :delete, data: {confirm: "¿Borrar categoría?: #{@category.nombre}?"}, class: "btn btn-danger btn-sm ml-1" do %>' +
    '<span class="fas fa-trash"></span>' +
    '<% end %>' +
    '</td>'+
    '</tr>'
)

app/views/categories/destroy.js.erb
$('#categoria_<%= @category.id %>').fadeOut();

app/views/categories/edit.js.erb
// Add the dialog title
$('#modal-categories-title').html('Modificar Categoría');

// Render the new form
$('.modal-body-categories').html('<%= j render("form") %>');

// Show the dynamic dialog // Set Focus to the first element
$(function(){
    $('#modalCategories').on('shown.bs.modal', function(){
        $(this).find('#category_nombre').focus();
    });
});

app/views/categories/index.html.erb
<h3 class="h3 mb-2 text-gray-800">Categorías de productos</h3>

<div>
  <%= link_to new_category_path, remote: true, class: 'btn btn-info', id:'anadir-categoria-btn', data: {'bs-toggle': 'modal', 'bs-target': '#modalCategories'} do %>
    <span class="fas fa-plus-square"></span>
  <% end %>
</div>

<br>

<div class="card shadow mb-4">
  <div class="cart-body">
    <div class="table-responsive">
      <table class="table table-bordered mb-0" id="tablaCategories" style="width: 100%;">
        <thead>
        <tr>
          <th>Nombre Categoría</th>
          <th>Descripción</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
          <% @categories.each do |cat| %>
            <tr id="categoria_<%= cat.id %>">
              <td><%= cat.nombre %></td>
              <td><%= truncate(cat.descripcion, length: 150) %></td>
              <td>
                <%= link_to edit_category_path(cat), remote: true, class: 'btn btn-info btn-sm', data: {'bs-toggle': 'modal', 'bs-target': '#modalCategories'} do %>
                  <span class="fas fa-pencil"></span>
                <% end %>
                <%= link_to cat, remote: true, method: :delete, data: {confirm: "¿Borrar categoría?: #{cat.nombre}?"}, class: 'btn btn-danger btn-sm' do %>
                  <span class="fas fa-trash"></span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= render 'modal_categories' %>

app/views/categories/new.js.erb
// Add the dialog title
$('#modal-categories-title').html('Nueva Categoría');

// Render the new form
$('.modal-body-categories').html('<%= j render("form") %>');

// Show the dynamic dialog // Set Focus to the first element
$(function(){
   $('#modalCategories').on('shown.bs.modal', function(){
      $(this).find('#category_nombre').focus();
   });
});

app/views/categories/update.js.erb
$('#categoria_<%= @category.id %>').replaceWith(
    '<tr id="categoria_<%= @category.id %>">' +
    '<td><%= @category.nombre %></td>' +
    '<td><%= @category.descripcion %></td>' +
    '<td>' +
    '<%= link_to edit_category_path(@category), remote: true, class: "btn btn-info btn-sm", data: {"bs-toggle": "modal", "bs-target": "#modalCategories"} do %>' +
    '<span class="fas fa-pencil"></span>' +
    '<% end %>' +
    '<%= link_to @category, remote: true, method: :delete, data: {confirm: "¿Borrar categoría?: #{@category.nombre}?"}, class: "btn btn-danger btn-sm" do %>' +
    '<span class="fas fa-trash"></span>' +
    '<% end %>' +
    '</td>'+
    '</tr>'
)