config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  resources :categories, except: [:show]
  resources :clients, except: [:show]
  resources :suppliers, except: [:show]
  resources :products
  resources :sales
  resources :warehouses
  resources :profiles, only: %w[show edit update]

  get 'buscar_producto/:termino', to: 'products#buscador'
  get '/buscador_clientes/:termino', to: 'clients#buscador'
  get '/buscador_proveedores/:termino', to: 'suppliers#buscador'
  post 'add_item_venta', to: 'sales#add_item'
  post 'add_cliente_venta', to: 'sales#add_client'
  post 'add_item_almacen', to: 'warehouses#add_item'
  post 'add_proveedor_entrada', to: 'warehouses#add_proveedor'
  post '/search', to: 'search#results'
  get '/search', to: 'home#index'

  #match '*unmatched', to: 'application#not_found_method', via: %i[get post]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/sale.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: sales
#
#  id         :bigint           not null, primary key
#  importe    :decimal(, )
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  client_id  :bigint
#  user_id    :integer
#
# Indexes
#
#  index_sales_on_client_id  (client_id)
#
# Foreign Keys
#
#  fk_rails_...  (client_id => clients.id)
#
class Sale < ApplicationRecord
  belongs_to :client, optional: true
  belongs_to :user
  has_many :sale_details, dependent: :destroy
end

app/controllers/sales_controller.rb
# frozen_string_literal: true

# sales controller
class SalesController < ApplicationController
  before_action :set_sale, only: %i[show edit destroy add_item add_client]

  def index
    # @sales = Sale.all
    @sales = Sale.includes(%i[user client]) # recomendacion de bullet gem para prevenir query n+1
  end

  def new
    @sale = current_user.sales.create(importe: 0.0)
    redirect_to edit_sale_path(@sale)
  end

  def show; end

  def edit
    @products_sale = @sale.sale_details
  end

  def destroy
    ActiveRecord::Base.transaction do
      @sale.sale_details.map do |detail|
        prod_vendido = Product.find(detail.product_id)
        prod_vendido.existencia += detail.cantidad
        ActiveRecord::Rollback unless prod_vendido.save
      end

      ActiveRecord::Rollback unless @sale.destroy
    end

    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'La venta ha sido eliminada' }
      format.json { head :no_content }
    end
  end

  # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
  def add_item
    producto = Product.find(params[:producto_id])
    cantidad = params[:cantidad].nil? ? 1 : params[:cantidad].to_i
    importe_producto = producto.precio * cantidad
    @sale_detail = @sale.sale_details.build(product: producto, cantidad: cantidad)
    importe_antes_de_registro = @sale.importe
    importe_despues_de_registro = importe_antes_de_registro + importe_producto
    @sale.importe = importe_despues_de_registro
    existencia_antes_venta = producto.existencia
    result = { product_id: @sale_detail.product_id, precio_producto: producto.precio,
               nombre_producto: @sale_detail.product&.nombre, cantidad: @sale_detail.cantidad,
               importe_item: producto.precio * cantidad, importe_venta: importe_despues_de_registro }
    producto.existencia = existencia_antes_venta - cantidad
    respond_to do |format|
      if @sale.save && producto.save
        format.json { render json: result }
      else
        format.json { render json: @sale.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end
  # rubocop:enable Metrics/AbcSize, Metrics/MethodLength

  def add_client
    cliente = Client.find(params[:cliente_id])

    if cliente.present?
      @sale.client = cliente
      if @sale.valid?
        result = { nombre_cliente: @sale.client.try(:nombre) }

        respond_to do |format|
          if @sale.save
            format.json { render json: result }
          else
            format.json { render json: @sale.errors.full_messages, status: :unprocessable_entity }
          end
        end
      end
    else
      render json: { message: 'El cliente no se encontró' }, status: :not_found
    end
  end

  private

  def set_sale
    @sale = Sale.find(params[:id])
  end
end

app/views/sales/_modal_sales.html.erb
<!-- Modal -->
<div class="modal fade" id="modalSales" tabindex="-1" role="dialog" aria-labelledby="modalSalesLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-sales-title">Modal title</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body-sales modal-body" id="modal-body-sales">

      </div>
      <div class="modal-footer" id="modal-footer-sales">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/sales/_sale.html.erb
<form class="form-floating mb-3">
  <div class="row">
    <div class="mb-3 col-md-6">
      <label for="id">ID</label>
      <input type="text" class="form-control" id="id" value="<%= @sale.id %>" disabled>
    </div>
    <div class="mb-3 col-md-6">
      <label for="date">Fecha</label>
      <input type="text" class="form-control" id="date" value="<%= l(@sale.created_at, format:"%d-%m-%Y") %>" disabled>
    </div>
  </div>
  <div class="row">
    <div class="mb-3 col-md-6">
      <label for="sale-amount">Monto de venta</label>
      <input type="text" class="form-control" id="sale-amount" value="<%= @sale.importe %>" disabled>
    </div>
    <div class="mb-3 col-md-6">
      <label for="seller">Vendedor</label>
      <input type="text" class="form-control" id="seller" value="<%= @sale.user.nombre %>" disabled>
    </div>
  </div>
</form>
<br>
<table class="table table-dark">
  <thead>
    <tr>
      <th>Producto</th>
      <th>Cantidad</th>
      <th>Precio</th>
      <th>Importe</th>
    </tr>
  </thead>
  <tbody>
    <% @sale.sale_details.each do |detalle| %>
      <tr>
        <td><%= detalle.product.nombre %></td>
        <td><%= detalle.cantidad %></td>
        <td><%= detalle.product.precio %></td>
        <td><%= detalle.product.precio * detalle.cantidad %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sales/edit.html.erb
<%=  stylesheet_pack_tag 'sales' %>
<div class="row">
  <div class="col-md-6">
    <h3 class="h3 mb-2 text-gray-800">Punto de venta</h3>
  </div>
  <div class="col-md-6" style="text-align: right;">
    <h2 id="importe_venta_lbl">Importe $<%= @sale.importe %></h2>
  </div>
  <div class="col-md-5">
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#buscar_producto">
      Buscar producto
    </button>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#buscar_cliente">
      Buscar cliente
    </button>
  </div>
  <div class="col-md-7" style="text-align: right;">
    <%= link_to 'Finalizar venta', sales_path, class: 'btn btn-success' %>
    <%= link_to 'Cancelar venta', @sale, method: :delete, data: {confirm: '¿Cancelar la venta?'}, class: 'btn btn-danger' %>
  </div>
  <div id="cliente_venta" class="nombre-cliente col-md-3">
    Cliente: <%= @sale.client.present? ? @sale.client&.nombre : "Consumidor Final" %>
  </div>
</div>
<br>
<div class="card shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="tabla_ventas" width="80%" cellspacing="0">
        <thead>
          <tr>
            <th>Producto</th>
            <th>Precio Unitario</th>
            <th>Cantidad</th>
            <th>Importe</th>
          </tr>
        </thead>
        <tbody>
          <% if !@products_sale.present? %>
            <tr>
              <td>No hay productos en la venta</td>
              <td></td>
              <td></td>
              <td></td>
            </tr>
          <% else %>
            <% @products_sale.each do |det| %>
              <tr>
                <td><%= det.product&.nombre %></td>
                <td><%= det.product&.precio %></td>
                <td><%= det.cantidad %></td>
                <td>$ <%= det.product&.precio * det.cantidad %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%
  @model = @sale
  @tipo = 'sales'
%>

<%= render 'buscar_producto', model: @model, tipo: @tipo %>
<%= render 'buscar_cliente', sale: @sale%>

app/views/sales/index.html.erb
<%= link_to new_sale_path, class: 'btn btn-info', id: 'crear-venta-btn' do %>
  <span class="fas fa-plus-square"></span> Realizar venta
<% end %>
<br><br>
<div class="card shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="tabla_ventas" width="60%" cellspacing="0">
        <thead>
        <tr>
          <th>Id</th>
          <th>Vendedor</th>
          <th>Cliente</th>
          <th>Importe</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
          <% if !@sales.present? %>
            <tr>
              <td>No hay ventas</td>
              <td></td>
              <td></td>
            </tr>
          <% else %>
            <% @sales.each do |sale| %>
              <tr>
                <td><%= sale.id %></td>
                <td><%= sale.user.nombre.present? ? sale.user.nombre : sale.user.email %></td>
                <td><%= sale.client&.nombre %></td>
                <td><%= sale.importe %></td>
                <td>
                  <%= link_to sale_path(sale), class: 'btn btn-info btn-xs', data: {'bs-toggle': 'modal', 'bs-target': '#modalSales'}, remote: true do %>
                    <i class="fas fa-info"></i>
                  <% end %>
                  <%= link_to 'X', sale, method: :delete, data: {confirm: 'Eliminar venta?'}, class: 'btn btn-danger btn-xs'  %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= render 'modal_sales' %>

app/views/sales/show.js.erb
// Add the dialog title
$('#modal-sales-title').html('Detalle de la Venta');

// Render the new form
$('.modal-body-sales').html('<%= j render("sale") %>');

// Show the dynamic dialog // Set Focus to the first element
$(function(){
    $('#modalSales').on('shown.bs.modal', function(){
        $(this).find('#sale_nombre').focus();
    });
});