config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  resources :categories, except: [:show]
  resources :clients, except: [:show]
  resources :suppliers, except: [:show]
  resources :products
  resources :sales
  resources :warehouses
  resources :profiles, only: %w[show edit update]

  get 'buscar_producto/:termino', to: 'products#buscador'
  get '/buscador_clientes/:termino', to: 'clients#buscador'
  get '/buscador_proveedores/:termino', to: 'suppliers#buscador'
  post 'add_item_venta', to: 'sales#add_item'
  post 'add_cliente_venta', to: 'sales#add_client'
  post 'add_item_almacen', to: 'warehouses#add_item'
  post 'add_proveedor_entrada', to: 'warehouses#add_proveedor'
  post '/search', to: 'search#results'
  get '/search', to: 'home#index'

  #match '*unmatched', to: 'application#not_found_method', via: %i[get post]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright &copy; Your Website 2021</span>
    </div>
  </div>
</footer>
<!-- End of Footer -->

app/views/layouts/_logout_modal.html.erb
<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Cerrar Sesión</h5>
        <button class="close" type="button" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">Para cerrar la sesión actual, haga click en "cerrar sesión".</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Cancelar</button>
        <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_side_bar.html.erb
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <%= link_to root_path , class:'sidebar-brand d-flex align-items-center justify-content-center' do %>
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-kiss-wink-heart"></i>
    </div>
    <div class="sidebar-brand-text mx-3">Sys Admin <sup>v1.1</sup></div>
  <% end %>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Modulos
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <%= link_to categories_path, class: 'nav-link' do %>
      <i class="fas fa-tags"></i>
      <span>Categorías</span>
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to products_path, class: 'nav-link' do %>
      <i class="fas fa-boxes-packing"></i>
      <span>Productos</span>
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to clients_path, class: 'nav-link' do %>
      <i class="fas fa-users"></i>
      <span>Clientes</span>
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to suppliers_path, class: 'nav-link' do %>
      <i class="fas fa-truck"></i>
      <span>Proveedores</span>
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to sales_url, class: 'nav-link' do %>
      <i class="fas fa-shopping-cart"></i>
      <span>Ventas</span>
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to warehouses_url, class: 'nav-link' do %>
      <i class="fas fa-warehouse"></i>
      <span>Almacén</span>
    <% end %>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>
</ul>
<!-- End of Sidebar -->

app/views/layouts/_top_bar.html.erb
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  <!-- Topbar Search -->
  <% if controller_name != 'profiles' %>
    <%= form_with url: 'search' , class:"d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" do |form| %>
      <%= form.text_field :termino, label: false, class: 'form-control bg-light border-0 small', placeholder: 'buscar' %>
      <button class="btn btn-primary" type="submit">
        <i class="fas fa-search fa-sm"></i>
      </button>
    <% end %>
  <% end %>
  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">

    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
    <li class="nav-item dropdown no-arrow d-sm-none">
      <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
         data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-search fa-fw"></i>
      </a>
      <!-- Dropdown - Messages -->
      <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
           aria-labelledby="searchDropdown">
        <form class="form-inline mr-auto w-100 navbar-search">
          <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small"
                   placeholder="Search for..." aria-label="Search"
                   aria-describedby="basic-addon2">
            <div class="input-group-append">
              <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </li>



    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
         data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small">
          <% if current_user.nombre.present? %>
            <%= current_user.nombre %>
          <% else %>
            Usuario
          <% end %>
        </span>
        <%= image_tag(current_user.profile.profile_image.present? ? rails_blob_path(current_user.profile.profile_image) : 'undraw_profile.png', class: 'img-profile rounded-circle') %>
      </a>
      <!-- Dropdown - User Information -->
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
           aria-labelledby="userDropdown">
        <% cache current_user.profile.profile_image do %>
          <%= link_to profile_path(current_user), class: 'dropdown-item' do %>
            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i> Perfil
          <% end %>
        <% end %>

        <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#logoutModal">
          <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
          Salir
        </a>
      </div>
    </li>

  </ul>

</nav>
<!-- End of Topbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sistema Administrativo</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body id="page-top">
  <div id="wrapper">

    <%= render 'layouts/side_bar' %>

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <%= render 'layouts/top_bar' %>

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <%= yield %>

        </div>

      </div>
      <!-- End of Main Content -->

      <%= render 'layouts/footer' %>

    </div>
    <!-- End of Content Wrapper -->
  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <%= render 'layouts/logout_modal' %>

  <script type="text/javascript" charset="utf-8">
      $(document).ready(function () {
          console.log('jquery funciona')
      });
  </script>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="es">

<head>
  <title>Sistema Administrativo</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="bg-gradient-primary">

<div class="container">

  <!-- Outer Row -->
  <div class="row justify-content-center">

    <div class="col-xl-10 col-lg-12 col-md-9">

      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-6 d-none d-lg-block bg-login-image" style="background: url(<%= image_url('pug_image.webp') %>)"></div>
            <div class="col-lg-6">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                </div>

                <%= yield %>

              </div>
            </div>
          </div>
        </div>
      </div>

    </div>

  </div>

</div>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function () {
        console.log('jquery funciona')
    });
</script>

</body>

</html>